#ifndef QTKPLUGINGENERATORCORE_GLOBAL_H
#define QTKPLUGINGENERATORCORE_GLOBAL_H

#include <qglobal.h>
#include <QLoggingCategory>

#if defined(QTK_PLUGINGENERATORCORE_LIBRARY)
#  define QTK_PLUGINGENERATORCORE_EXPORT Q_DECL_EXPORT
#else
#  define QTK_PLUGINGENERATORCORE_EXPORT Q_DECL_IMPORT
#endif

#endif // QTKPLUGINGENERATORCORE_GLOBAL_H
