#ifndef QEXTDEVICEWATCHER_GLOBAL_H
#define QEXTDEVICEWATCHER_GLOBAL_H

#include <qglobal.h>
#include <QLoggingCategory>

#if defined(QEXT_DEVICEWATCHER_LIBRARY)
#  define QEXT_DEVICEWATCHER_EXPORT Q_DECL_EXPORT
#else
#  define QEXT_DEVICEWATCHER_EXPORT Q_DECL_IMPORT
#endif

#endif // QEXTDEVICEWATCHER_GLOBAL_H
