#ifndef _QEXTMVVMSIGNALSITEMLISTENERBASE_H
#define _QEXTMVVMSIGNALSITEMLISTENERBASE_H

#include <qextMvvmGlobal.h>
#include <qextMvvmCallbackTypes.h>

namespace ModelView
{

class QEXTMvvmSessionItem;

//! Provides sets of methods to subscribe to various signals generated by QEXTMvvmSessionItem.
//! Used to implement user actions on item change.

//! Automatically tracks the time of life of QEXTMvvmSessionItem. Unsubscribes from the item on
//! own destruction. Can be switched from tracking one item to another of the same type.

class QEXT_MVVM_API QEXTMvvmItemListenerBase
{
public:
    explicit QEXTMvvmItemListenerBase(QEXTMvvmSessionItem* item = nullptr);
    virtual ~QEXTMvvmItemListenerBase();

    QEXTMvvmItemListenerBase& operator=(const QEXTMvvmItemListenerBase& other) = delete;
    QEXTMvvmItemListenerBase(const QEXTMvvmItemListenerBase& other) = delete;

    void setItem(QEXTMvvmSessionItem* item);

    void setOnItemDestroy(QEXTMvvmCallbacks::item_t f);
    void setOnDataChange(QEXTMvvmCallbacks::item_int_t f);
    void setOnPropertyChange(QEXTMvvmCallbacks::item_str_t f);
    void setOnChildPropertyChange(QEXTMvvmCallbacks::item_str_t f);
    void setOnItemInserted(QEXTMvvmCallbacks::item_tagrow_t f);
    void setOnItemRemoved(QEXTMvvmCallbacks::item_tagrow_t f);
    void setOnAboutToRemoveItem(QEXTMvvmCallbacks::item_tagrow_t f);

protected:
    virtual void subscribe() {}   //! For necessary manipulations on new item.
    virtual void unsubscribe() {} //! For necessary manipulations on unsubscription.
    QEXTMvvmSessionItem* item() const;

private:
    void unsubscribe_from_current();
    QEXTMvvmSessionItem* m_item{nullptr};
};

} // namespace ModelView

#endif // _QEXTMVVMSIGNALSITEMLISTENERBASE_H
