#ifndef _QEXTMVVMSIGNALSITEMLISTENER_H
#define _QEXTMVVMSIGNALSITEMLISTENER_H

#include <qextMvvmItemListenerBase.h>

namespace ModelView
{

class QEXTMvvmSessionItem;

//! Base class to subscribe to signals generated by QEXTMvvmSessionItem of certin type.

template <typename T> class QEXTMvvmItemListener : public QEXTMvvmItemListenerBase
{
public:
    T* currentItem() const { return static_cast<T*>(item()); }
};

} // namespace ModelView

#endif // _QEXTMVVMSIGNALSITEMLISTENER_H
