#ifndef _QEXTMVVMMODELLISTENERBASE_H
#define _QEXTMVVMMODELLISTENERBASE_H

#include <qextMvvmModelListenerInterface.h>

namespace ModelView
{

class QEXTMvvmSessionModel;

//! Provides sets of methods to subscribe to various signals generated by QEXTMvvmSessionModel.
//! Automatically tracks the time of life of QEXTMvvmSessionModel. Unsubscribes from the model on
//! own destruction.

class QEXT_MVVM_API QEXTMvvmModelListenerBase : public QEXTMvvmModelListenerInterface
{
public:
    QEXTMvvmModelListenerBase(QEXTMvvmSessionModel* model);
    ~QEXTMvvmModelListenerBase() override;

    // 'client' is not used here, since 'this' is used

    void setOnDataChange(Callbacks::item_int_t f, Callbacks::slot_t client = {}) override;
    void setOnItemInserted(Callbacks::item_tagrow_t f, Callbacks::slot_t client = {}) override;
    void setOnItemRemoved(Callbacks::item_tagrow_t f, Callbacks::slot_t client = {}) override;
    void setOnAboutToRemoveItem(Callbacks::item_tagrow_t f, Callbacks::slot_t client = {}) override;
    void setOnModelDestroyed(Callbacks::model_t f, Callbacks::slot_t client = {}) override;
    void setOnModelAboutToBeReset(Callbacks::model_t f, Callbacks::slot_t client = {}) override;
    void setOnModelReset(Callbacks::model_t f, Callbacks::slot_t client = {}) override;

    void unsubscribe(Callbacks::slot_t client = {}) override;

protected:
    QEXTMvvmSessionModel* m_model{nullptr};
};

} // namespace ModelView

#endif // _QEXTMVVMMODELLISTENERBASE_H
