#ifndef _QEXTMVVMSIGNALSMODELLISTENERBASE_H
#define _QEXTMVVMSIGNALSMODELLISTENERBASE_H

#include <qextMvvmModelListenerInterface.h>

namespace ModelView
{

class QEXTMvvmSessionModel;

//! Provides sets of methods to subscribe to various signals generated by SessionModel.
//! Automatically tracks the time of life of SessionModel. Unsubscribes from the model on
//! own destruction.

class QEXT_MVVM_API QEXTMvvmModelListenerBase : public QEXTMvvmModelListenerInterface
{
public:
    QEXTMvvmModelListenerBase(QEXTMvvmSessionModel* model);
    ~QEXTMvvmModelListenerBase() override;

    // 'client' is not used here, since 'this' is used

    void setOnDataChange(QEXTMvvmCallbacks::item_int_t f, QEXTMvvmCallbacks::slot_t client = {}) override;
    void setOnItemInserted(QEXTMvvmCallbacks::item_tagrow_t f, QEXTMvvmCallbacks::slot_t client = {}) override;
    void setOnItemRemoved(QEXTMvvmCallbacks::item_tagrow_t f, QEXTMvvmCallbacks::slot_t client = {}) override;
    void setOnAboutToRemoveItem(QEXTMvvmCallbacks::item_tagrow_t f, QEXTMvvmCallbacks::slot_t client = {}) override;
    void setOnModelDestroyed(QEXTMvvmCallbacks::model_t f, QEXTMvvmCallbacks::slot_t client = {}) override;
    void setOnModelAboutToBeReset(QEXTMvvmCallbacks::model_t f, QEXTMvvmCallbacks::slot_t client = {}) override;
    void setOnModelReset(QEXTMvvmCallbacks::model_t f, QEXTMvvmCallbacks::slot_t client = {}) override;

    void unsubscribe(QEXTMvvmCallbacks::slot_t client = {}) override;

protected:
    QEXTMvvmSessionModel* m_model{nullptr};
};

} // namespace ModelView

#endif // _QEXTMVVMSIGNALSMODELLISTENERBASE_H
