#ifndef _QEXTMVVMMODELLISTENERINTERFACE_H
#define _QEXTMVVMMODELLISTENERINTERFACE_H

#include <qextMvvmGlobal.h>
#include <qextMvvmFunctionTypes.h>

class QEXTMvvmItem;
class QEXTMvvmModel;
class QEXTMvvmTagRow;

//! Interface to subscribe to various signals generated by QEXTMvvmModel.

class QEXT_MVVM_API QEXTMvvmModelListenerInterface
{
public:
    virtual ~QEXTMvvmModelListenerInterface() {}

    virtual QEXTConnection addItemAboutToBeInsertedListener(QEXTMvvmItemTagRowFunction function, void *listener = QEXT_DECL_NULLPTR) = 0;
    virtual QEXTConnection addItemInsertedListener(QEXTMvvmItemTagRowFunction function, void *listener = QEXT_DECL_NULLPTR) = 0;

    virtual QEXTConnection addItemAboutToBeRemovedListener(QEXTMvvmItemTagRowFunction function, void *listener = QEXT_DECL_NULLPTR) = 0;
    virtual QEXTConnection addItemRemovedListener(QEXTMvvmItemTagRowFunction function, void *listener = QEXT_DECL_NULLPTR) = 0;

    virtual QEXTConnection addItemDataAboutToBeChangedListener(QEXTMvvmItemRoleFunction function, void *listener = QEXT_DECL_NULLPTR) = 0;
    virtual QEXTConnection addItemDataChangedListener(QEXTMvvmItemRoleFunction function, void *listener = QEXT_DECL_NULLPTR) = 0;

    virtual QEXTConnection addItemAboutToBeDestroyedListener(QEXTMvvmItemFunction function, void *listener = QEXT_DECL_NULLPTR) = 0;
    virtual QEXTConnection addItemDestroyedListener(QEXTMvvmItemFunction function, void *listener = QEXT_DECL_NULLPTR) = 0;

    virtual QEXTConnection addModelAboutToBeDestroyedListener(QEXTMvvmModelFunction function, void *listener = QEXT_DECL_NULLPTR) = 0;
    virtual QEXTConnection addModelDestroyedListener(QEXTMvvmModelFunction function, void *listener = QEXT_DECL_NULLPTR) = 0;

    virtual QEXTConnection addModelAboutToBeResetedListener(QEXTMvvmModelFunction function, void *listener = QEXT_DECL_NULLPTR) = 0;
    virtual QEXTConnection addModelResetedListener(QEXTMvvmModelFunction function, void *listener = QEXT_DECL_NULLPTR) = 0;

    virtual void removeListener(void *listener = QEXT_DECL_NULLPTR) = 0;
};


#endif // _QEXTMVVMMODELLISTENERINTERFACE_H
