#ifndef _QEXTDACONSTANTS_H
#define _QEXTDACONSTANTS_H

#include <qextDAViewGlobal.h>

namespace QExtDAConstants
{
QEXT_STATIC_CONSTANT_STRING(IODEVICE_PROPERTY_ALIAS, "IODeviceAlias")
QEXT_STATIC_CONSTANT_STRING(IODEVICE_PROPERTY_STATE, "IODeviceState")
QEXT_STATIC_CONSTANT_STRING(IODEVICE_PROPERTY_PATH, "IODevicePath")
QEXT_STATIC_CONSTANT_STRING(IODEVICE_PROPERTY_BPS, "IODeviceBps")

QEXT_STATIC_CONSTANT_STRING(IODEVICE_TYPE_SERIALPORT, "SerialPort")
QEXT_STATIC_CONSTANT_STRING(IODEVICE_TYPE_UDPSOCKET, "UdpSocket")
QEXT_STATIC_CONSTANT_STRING(IODEVICE_TYPE_TCPSOCKET, "TcpSocket")

QEXT_STATIC_CONSTANT_NUMBER(IODEVICE_MAX_COUNT, 6)
}

#endif // _QEXTDACONSTANTS_H
