#ifndef _QEXTDACONSTANTS_H
#define _QEXTDACONSTANTS_H

#include <qextDAViewGlobal.h>

namespace QExtDAConstants
{
QEXT_STATIC_CONSTANT_NUMBER(IODEVICE_MAX_COUNT, 6)

QEXT_STATIC_CONSTANT_STRING(IODEVICE_TYPE_UDPSOCKET, "UdpSocket")
QEXT_STATIC_CONSTANT_STRING(IODEVICE_TYPE_TCPSOCKET, "TcpSocket")
QEXT_STATIC_CONSTANT_STRING(IODEVICE_TYPE_SERIALPORT, "SerialPort")

QEXT_STATIC_CONSTANT_STRING(IODEVICE_PROPERTY_BPS, "Bps")
QEXT_STATIC_CONSTANT_STRING(IODEVICE_PROPERTY_PATH, "Path")
QEXT_STATIC_CONSTANT_STRING(IODEVICE_PROPERTY_STATE, "State")

QEXT_STATIC_CONSTANT_STRING(IODEVICE_PROPERTY_ID, "Id")
QEXT_STATIC_CONSTANT_STRING(IODEVICE_PROPERTY_TYPE, "Type")
QEXT_STATIC_CONSTANT_STRING(IODEVICE_PROPERTY_ALIAS, "Alias")
QEXT_STATIC_CONSTANT_STRING(IODEVICE_PROPERTY_BUFFER_SIZE, "BufferSize")
QEXT_STATIC_CONSTANT_STRING(IODEVICE_PROPERTY_BUFFER_ENABLED, "BufferEnabled")

QEXT_STATIC_CONSTANT_STRING(SERIALPORT_IODEVICE_PROPERTY_PARITY, "Parity")
QEXT_STATIC_CONSTANT_STRING(SERIALPORT_IODEVICE_PROPERTY_BAUD_RATE, "BaudRate")
QEXT_STATIC_CONSTANT_STRING(SERIALPORT_IODEVICE_PROPERTY_STOP_BITS, "StopBits")
QEXT_STATIC_CONSTANT_STRING(SERIALPORT_IODEVICE_PROPERTY_DATA_BITS, "DataBits")
QEXT_STATIC_CONSTANT_STRING(SERIALPORT_IODEVICE_PROPERTY_PORT_NAME, "PortName")
QEXT_STATIC_CONSTANT_STRING(SERIALPORT_IODEVICE_PROPERTY_FLOW_CONTROL, "FlowControl")

QEXT_STATIC_CONSTANT_STRING(TCPSOCKET_IODEVICE_PROPERTY_REMOTE_IP, "RemoteIP")
QEXT_STATIC_CONSTANT_STRING(TCPSOCKET_IODEVICE_PROPERTY_REMOTE_PORT, "RemotePort")

QEXT_STATIC_CONSTANT_STRING(UDPSOCKET_IODEVICE_PROPERTY_REMOTE_IP, "RemoteIP")
QEXT_STATIC_CONSTANT_STRING(UDPSOCKET_IODEVICE_PROPERTY_REMOTE_PORT, "RemotePort")
QEXT_STATIC_CONSTANT_STRING(UDPSOCKET_IODEVICE_PROPERTY_LOCAL_PORT, "LocalPort")

}

#endif // _QEXTDACONSTANTS_H
