#ifndef _QEXTMVVMITEMLISTENERBASE_H
#define _QEXTMVVMITEMLISTENERBASE_H

#include <qextMvvmGlobal.h>
#include <qextMvvmItemListenerInterface.h>

class QEXTMvvmItem;

//! Provides sets of methods to subscribe to various signals generated by QEXTMvvmItem.
//! Used to implement user actions on item change.

//! Automatically tracks the time of life of QEXTMvvmItem. Unsubscribes from the item on
//! own destruction. Can be switched from tracking one item to another of the same type.

class QEXT_MVVM_API QEXTMvvmItemListenerBase : public QEXTMvvmItemListenerInterface
{
public:
    explicit QEXTMvvmItemListenerBase(QEXTMvvmItem *item = QEXT_DECL_NULLPTR);
    virtual ~QEXTMvvmItemListenerBase();

    QEXTConnection addItemAboutToBeInsertedListener(QEXTMvvmItemTagRowFunction function, void *listener = QEXT_DECL_NULLPTR) QEXT_DECL_OVERRIDE;
    QEXTConnection addItemInsertedListener(QEXTMvvmItemTagRowFunction function, void *listener = QEXT_DECL_NULLPTR) QEXT_DECL_OVERRIDE;

    QEXTConnection addItemAboutToBeRemovedListener(QEXTMvvmItemTagRowFunction function, void *listener = QEXT_DECL_NULLPTR) QEXT_DECL_OVERRIDE;
    QEXTConnection addItemRemovedListener(QEXTMvvmItemTagRowFunction function, void *listener = QEXT_DECL_NULLPTR) QEXT_DECL_OVERRIDE;

    QEXTConnection addItemDataAboutToBeChangedListener(QEXTMvvmItemRoleFunction function, void *listener = QEXT_DECL_NULLPTR) QEXT_DECL_OVERRIDE;
    QEXTConnection addItemDataChangedListener(QEXTMvvmItemRoleFunction function, void *listener = QEXT_DECL_NULLPTR) QEXT_DECL_OVERRIDE;

    QEXTConnection addItemAboutToBeDestroyedListener(QEXTMvvmItemFunction function, void *listener = QEXT_DECL_NULLPTR) QEXT_DECL_OVERRIDE;
    QEXTConnection addItemDestroyedListener(QEXTMvvmItemFunction function, void *listener = QEXT_DECL_NULLPTR) QEXT_DECL_OVERRIDE;

    QEXTConnection addItemPropertyAboutToBeChangedListener(QEXTMvvmItemPropertyFunction function, void *listener = QEXT_DECL_NULLPTR) QEXT_DECL_OVERRIDE;
    QEXTConnection addItemPropertyChangedListener(QEXTMvvmItemPropertyFunction function, void *listener = QEXT_DECL_NULLPTR) QEXT_DECL_OVERRIDE;

    QEXTConnection addItemChildPropertyAboutToBeChangedListener(QEXTMvvmItemPropertyFunction function, void *listener = QEXT_DECL_NULLPTR) QEXT_DECL_OVERRIDE;
    QEXTConnection addItemChildPropertyChangedListener(QEXTMvvmItemPropertyFunction function, void *listener = QEXT_DECL_NULLPTR) QEXT_DECL_OVERRIDE;

    void removeListener(void *listener = QEXT_DECL_NULLPTR) QEXT_DECL_OVERRIDE;

    void setItem(QEXTMvvmItem* item);

protected:
    virtual void subscribe() {}   //! For necessary manipulations on new item.
    virtual void unsubscribe() {} //! For necessary manipulations on unsubscription.

    QEXTMvvmItem *item() const;

private:
    void unsubscribeFromCurrent();
    void onItemDestroy(QEXTMvvmItem *);

    QEXTMvvmItem *m_item;
};

#endif // _QEXTMVVMITEMLISTENERBASE_H
