#ifndef _QEXTMVVMMODELLISTENERBASE_H
#define _QEXTMVVMMODELLISTENERBASE_H

#include <qextMvvmModelListenerInterface.h>

class QEXTMvvmModel;

//! Provides sets of methods to subscribe to various signals generated by QEXTMvvmModel.
//! Automatically tracks the time of life of QEXTMvvmModel. Unsubscribes from the model on
//! own destruction.

class QEXT_MVVM_API QEXTMvvmModelListenerBase : public QEXTMvvmModelListenerInterface
{
public:
    QEXTMvvmModelListenerBase(QEXTMvvmModel *model);
    ~QEXTMvvmModelListenerBase() QEXT_DECL_OVERRIDE;

    QEXTConnection addItemAboutToBeInsertedListener(QEXTMvvmItemTagRowFunction function, void *listener = QEXT_DECL_NULLPTR) QEXT_DECL_OVERRIDE;
    QEXTConnection addItemInsertedListener(QEXTMvvmItemTagRowFunction function, void *listener = QEXT_DECL_NULLPTR) QEXT_DECL_OVERRIDE;

    QEXTConnection addItemAboutToBeRemovedListener(QEXTMvvmItemTagRowFunction function, void *listener = QEXT_DECL_NULLPTR) QEXT_DECL_OVERRIDE;
    QEXTConnection addItemRemovedListener(QEXTMvvmItemTagRowFunction function, void *listener = QEXT_DECL_NULLPTR) QEXT_DECL_OVERRIDE;

    QEXTConnection addItemDataAboutToBeChangedListener(QEXTMvvmItemRoleFunction function, void *listener = QEXT_DECL_NULLPTR) QEXT_DECL_OVERRIDE;
    QEXTConnection addItemDataChangedListener(QEXTMvvmItemRoleFunction function, void *listener = QEXT_DECL_NULLPTR) QEXT_DECL_OVERRIDE;

    QEXTConnection addItemAboutToBeDestroyedListener(QEXTMvvmItemFunction function, void *listener = QEXT_DECL_NULLPTR) QEXT_DECL_OVERRIDE;
    QEXTConnection addItemDestroyedListener(QEXTMvvmItemFunction function, void *listener = QEXT_DECL_NULLPTR) QEXT_DECL_OVERRIDE;

    QEXTConnection addModelAboutToBeDestroyedListener(QEXTMvvmModelFunction function, void *listener = QEXT_DECL_NULLPTR) QEXT_DECL_OVERRIDE;
    QEXTConnection addModelDestroyedListener(QEXTMvvmModelFunction function, void *listener = QEXT_DECL_NULLPTR) QEXT_DECL_OVERRIDE;

    QEXTConnection addModelAboutToBeResetedListener(QEXTMvvmModelFunction function, void *listener = QEXT_DECL_NULLPTR) QEXT_DECL_OVERRIDE;
    QEXTConnection addModelResetedListener(QEXTMvvmModelFunction function, void *listener = QEXT_DECL_NULLPTR) QEXT_DECL_OVERRIDE;

    void removeListener(void *listener = QEXT_DECL_NULLPTR) QEXT_DECL_OVERRIDE;

protected:
    QEXTMvvmModel* m_model{nullptr};
};

#endif // _QEXTMVVMMODELLISTENERBASE_H
