#ifndef _QEXTMVVMITEMLISTENER_H
#define _QEXTMVVMITEMLISTENER_H

#include <qextMvvmItemListenerBase.h>

class QEXTMvvmItem;

//! Base class to subscribe to signals generated by QEXTMvvmItem of certin type.

template <typename T> class QEXTMvvmItemListener : public QEXTMvvmItemListenerBase
{
public:
    T* currentItem() const { return static_cast<T*>(this->item()); }
};

#endif // _QEXTMVVMITEMLISTENER_H
