#ifndef QTKPLUGINGENERATORUI_GLOBAL_H
#define QTKPLUGINGENERATORUI_GLOBAL_H

#include <qglobal.h>
#include <QLoggingCategory>

#if defined(QTK_PLUGINGENERATORUI_LIBRARY)
#  define QTK_PLUGINGENERATORUI_EXPORT Q_DECL_EXPORT
#else
#  define QTK_PLUGINGENERATORUI_EXPORT Q_DECL_IMPORT
#endif

#endif // QTKPLUGINGENERATORUI_GLOBAL_H
