#ifndef _QEXTPLOTCONSTANTS_H
#define _QEXTPLOTCONSTANTS_H

#include <qextPlotGlobal.h>

namespace QExtPlotConstants
{
QEXT_STATIC_CONSTANT_STRING(PLOT_TYPE_BASE, "Plot")
QEXT_STATIC_CONSTANT_STRING(PLOT_TYPE_CURVE, "CurvePlot")


QEXT_STATIC_CONSTANT_STRING(PLOT_PROPERTY_TITLE, "Title")
QEXT_STATIC_CONSTANT_STRING(PLOT_PROPERTY_WIDTH, "Width")
QEXT_STATIC_CONSTANT_STRING(PLOT_PROPERTY_VISIBLE, "Visible")
QEXT_STATIC_CONSTANT_STRING(PLOT_PROPERTY_XAXIS_GRID_VISIBLE, "XAxisGridVisible")
QEXT_STATIC_CONSTANT_STRING(PLOT_PROPERTY_XAXIS_MINOR_GRID_VISIBLE, "XAxisMinorGridVisible")
QEXT_STATIC_CONSTANT_STRING(PLOT_PROPERTY_YAXIS_GRID_VISIBLE, "YAxisGridVisible")
QEXT_STATIC_CONSTANT_STRING(PLOT_PROPERTY_YAXIS_MINOR_GRID_VISIBLE, "YAxisMinorGridVisible")
QEXT_STATIC_CONSTANT_STRING(PLOT_PROPERTY_XAXIS_RANGE, "XAxisRange")
QEXT_STATIC_CONSTANT_STRING(PLOT_PROPERTY_XAXIS_RANGE_MIN, "XAxisRangeMin")
QEXT_STATIC_CONSTANT_STRING(PLOT_PROPERTY_XAXIS_RANGE_MAX, "YAxisRangeMax")
QEXT_STATIC_CONSTANT_STRING(PLOT_PROPERTY_YAXIS_RANGE, "YAxisRange")
QEXT_STATIC_CONSTANT_STRING(PLOT_PROPERTY_YAXIS_RANGE_MIN, "YAxisRangeMin")
QEXT_STATIC_CONSTANT_STRING(PLOT_PROPERTY_YAXIS_RANGE_MAX, "YAxisRangeMax")
QEXT_STATIC_CONSTANT_STRING(PLOT_PROPERTY_XAXIS_AUTO_SCALED, "XAxisAutoScaled")
QEXT_STATIC_CONSTANT_STRING(PLOT_PROPERTY_YAXIS_AUTO_SCALED, "YAxisAutoScaled")

}

#endif // _QEXTPLOTCONSTANTS_H
